server:
  port: 8011

spring:
  application:
    name: av-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 4
  cloud:
    nacos:
      discovery:
        server-addr: 211.101.236.212:8848
        namespace: public
        username: nacos
        password: nacos

# RocketMQ 配置
rocketmq:
  name-server: 211.101.236.212:9876
  producer:
    group: av_producer_group

# 日志
logging:
  level:
    root: INFO
    com.example.av: DEBUG
